### ISSUE TITLE
[Request] Publish arm64 based docker image

### ISSUE THREAD

**Issue by Strit** [tyrsarm/peertube-headless-seeder#1]
Some people might have arm based hardware, that are on 24/7, which would be great seedboxes for something like this.

But the current docker image is amd64 only.

So I would like to request an arm64 based image, maybe even armhf too.

**Comment by Migelo** [comment]
I did it in my [fork](https://github.com/Migelo/peertube-headless-seeder).
You can run it with:
`docker run --rm migel0/peertube-headless-seeder:latest`
