### ISSUE TITLE
No Latest Tag on Docker Hub

### ISSUE THREAD

**Issue by eroc1990** [tyrsarm/peertube-headless-seeder#2]
As it's configuired now, your docker run and docker compose scripts are set to pull from the :latest tag, but there is no :latest tag available, so pulls fail unless you specify :v0.1, the only tag avaialble. Can you add a :latest tag?

**Comment by Strit** [comment]
Having a `latest` tag would be preferable, but at least change the docker-compose example in the README to use an existing tag. :smile:

**Comment by davralin** [comment]
I corrected the readme, added in #3
